# Starship prompt - Catppuccin Macchiato theme
add_newline = false
format = """
$username$directory$git_branch$git_status$cmd_duration
$character"""

[username]
show_always = true
format = "[$user]($style) "
style_user = "#8AADF4"
style_root = "#ED8796"

[directory]
format = "[$path]($style) "
style = "#F5BDE6"
truncation_length = 0
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style)"
symbol = " "
style = "#B7BDF8"

[git_status]
format = '([$ahead_behind](#88C0D0) )([*$modified](#FFAFD7) )([$staged](#B7BDF8) )([$stashed](#B7BDF8) )'
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
modified = "${count}"
staged = " ${count}"
stashed = "󰊢 ${count}"

[cmd_duration]
format = "[ $duration]($style) "
style = "#A3BE8C"
min_time = 500

[character]
success_symbol = "[❯](#B48EAD)"
error_symbol = "[❯](#BF616A)"
